project_id = "bnkbnpiuzpftflfmnsge"

[functions.migrate-user-on-login]
verify_jwt = false

[functions.admin-update-profile]
verify_jwt = false

[functions.admin-import-integrantes]
verify_jwt = false

[functions.admin-import-mensalidades]
verify_jwt = false

[functions.manage-screen-permissions]
verify_jwt = false

[functions.manage-evento]
verify_jwt = false

[functions.manage-presenca]
verify_jwt = false

[functions.reprocessar-snapshots]
verify_jwt = false

[functions.get-calendar-events]
verify_jwt = false