project_id = "bnkbnpiuzpftflfmnsge"

[functions.export-relatorio-cmd]
verify_jwt = false

[functions.cleanup-drive-files]
verify_jwt = false

[functions.migrate-user-on-login]
verify_jwt = false

[functions.admin-update-profile]
verify_jwt = false

[functions.admin-import-integrantes]
verify_jwt = false

[functions.admin-import-mensalidades]
verify_jwt = false

[functions.manage-screen-permissions]
verify_jwt = false

[functions.manage-evento]
verify_jwt = false

[functions.manage-presenca]
verify_jwt = false

[functions.reprocessar-snapshots]
verify_jwt = false

[functions.get-calendar-events]
verify_jwt = false

[functions.enviar-alerta-inadimplencia]
verify_jwt = true

[functions.verificar-alertas-diarios]
verify_jwt = false

[functions.acoes-sociais-enviar-form]
verify_jwt = false

[functions.log-system-event]
verify_jwt = false

[functions.cleanup-system-logs]
verify_jwt = false

[functions.import-acoes-sociais]
verify_jwt = false

[functions.read-google-sheet]
verify_jwt = false

[functions.manutencao-acoes-sociais]
verify_jwt = false
